name: CI Pipeline of the Helm Chart

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'helm'
      - '.github/workflows/helm-ci.yaml'

jobs:
  ci:
    name: Helm Chart CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint Chart
        run: helm lint ./helm

      - name: Helm Template Validation
        run: helm template user-management ./helm
